steps = input("Please enter your steps count seprated by spaces: ")
steps = list(map(int,steps.split( )))
max_steps = max(steps)
n = len(steps)
a = sum(steps)
min_steps = min(steps)
steps.sort(reverse=True)
print("Your max steps were: ", max_steps)
print("Your minumum steps were: ", min_steps)
print("Your Average steps were: ", a/n)
print("Your steps in descending order: ", steps)
#Explanation is in the readme file in the first link!
